# standalone mode
# https://cloud.spring.io/spring-cloud-netflix/multi/multi_spring-cloud-eureka-server.html
server:
  port: 8761
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
# actuator
management:
  security:
    enabled: false

---
spring:
  profiles: 1
server:
  port: 8761
# service discovery
eureka:
  instance:
    hostname: eureka-server-1
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-server-2:8762/eureka/

---
spring:
  profiles: 2
server:
  port: 8762
# service discovery
eureka:
  instance:
    hostname: eureka-server-2
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-server-1:8761/eureka/
