server:
  port: 8080
# service discovery
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server-1:8761/eureka/
spring:
  # message queue - connection - for spring cloud bus
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
# refresh scope
demo:
  refreshscope:
    hello: fares
# actuator
management:
  security:
    enabled: false

---
spring:
  profiles: 1
server:
  port: 8080

---
spring:
  profiles: 2
server:
  port: 8081

---
spring:
  profiles: 3
server:
  port: 8082

---
spring:
  profiles: 4
server:
  port: 8083

---
spring:
  profiles: ha
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server-load-balancer:8760/eureka/
