server:
  port: 8095
# service discovery
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server-1:8761/eureka/
# gateway
zuul:
  routes:
    search-apigateway:
      serviceId: search-service
      path: /api/**
# actuator
management:
  security:
    enabled: false

---
spring:
  profiles: 1
server:
  port: 8095

---
spring:
  profiles: 2
server:
  port: 8096

---
spring:
  profiles: ha
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server-load-balancer:8760/eureka/
