server:
  port: 8090
# service discovery
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server-1:8761/eureka/
spring:
  # message queue - connection
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  # message queue - queue
  cloud:
    stream:
      bindings:
        inventoryQ:
          destination: inventoryQ
# refresh scope
orginairports:
  shutdown: JFK
#  shutdown: NYC
demo:
  refreshscope:
    hello: search
# actuator
management:
  security:
    enabled: false

---
spring:
  profiles: 1
server:
  port: 8090

---
spring:
  profiles: 2
server:
  port: 8091

---
spring:
  profiles: 3
server:
  port: 8092

---
spring:
  profiles: 4
server:
  port: 8093

---
spring:
  profiles: ha
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server-load-balancer:8760/eureka/
